hazelcast/hazelcast-jet-contrib

build.gradle

Introduced the maven publisher plugin to publish artifacts to maven local and central
N/A

Added maven publisher plugin

---

influxdb/README.md

Added missing README for influxdb sink.
N/A
N/A

Added README for influxdb

---

build.gradle

Introduces snapshot repository to push snapshot artifacts to it.

Added snapshot repository

---

influxdb/README.md
influxdb/src/main/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSinks.java
influxdb/src/main/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSources.java
influxdb/src/main/java/com/hazelcast/jet/contrib/influxdb/MeasurementProjection.java
influxdb/src/main/java/com/hazelcast/jet/contrib/influxdb/package-info.java
influxdb/src/test/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSinkTest.java
influxdb/src/test/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSourceTest.java
influxdb/src/test/java/com/hazelcast/jet/contrib/influxdb/measurement/Cpu.java

Updates package names
- fixes #10

Updated package name to include contrib

---

build.gradle

Upgrades Jet to 3.1 and IMDG to 3.12.1

Upgrade jet to 3.1 and imdg to 3.12.1

---

build.gradle
elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/contrib/elasticsearch/ElasticsearchBaseTest.java
elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/contrib/elasticsearch/ElasticsearchBaseTest.java
elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/contrib/elasticsearch/ElasticsearchBaseTest.java
influxdb/src/test/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSinkTest.java
influxdb/src/test/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSourceTest.java

Added jacaco plugin to generate test coverage reports.
N/A

Added test coverage

---

templates/README.template.md

Introduced connector attributes to the README template
N/A

Added connector attributes

---

influxdb/README.md
influxdb/src/main/java/com/hazelcast/jet/contrib/influxdb/InfluxDbSources.java

Added small code snippets for javadocs and missing attributes table
N/A

Added javadoc code samples and connector attributes table

---

README.md
build.gradle
influxdb/README.md
redis/README.md
redis/build.gradle
redis/gradle.properties
redis/hash.md
redis/sorted_set.md
redis/src/main/java/com/hazelcast/jet/contrib/redis/RedisSinks.java
redis/src/main/java/com/hazelcast/jet/contrib/redis/RedisSources.java
redis/src/main/java/com/hazelcast/jet/contrib/redis/package-info.java
redis/src/test/java/com/hazelcast/jet/contrib/redis/RedisContainer.java
redis/src/test/java/com/hazelcast/jet/contrib/redis/RedisSinkTest.java
redis/src/test/java/com/hazelcast/jet/contrib/redis/RedisSourceTest.java
redis/src/test/resources/log4j.properties
redis/streams.md
settings.gradle

This PR adds Jet sources & sinks for Redis:
- Hash
- Sorted Set
- Streams

Add Redis sources & sinks

---

mongodb/README.md
mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinkBuilder.java
mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSourceBuilder.java
mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSources.java

- Documents restrictions of change streams for MongoDB
- Don't create a new list for each batch for MongoDB Sink

Don't create a new list for each batch for MongoDB Sink

---

build.gradle

Upgrades Hazelcast version to 4.0 final
- [NA] Documentation which complies with README template (see `templates/README.template.md`).
- [NA] Update `List of modules` section on the root README with your module.

Upgrade Hazelcast version to 4.0 final

---

kafka-connect/README.md
kafka-connect/src/main/java/com/hazelcast/jet/contrib/connect/KafkaConnectSources.java

Added note regarding Kafka Connect source connector parallelism

---

twitter/README.md

This PR updates the README.md of the Twitter Source. I added a usage guide to the Twitter Source.
- It fixes #40

Add a usage guide to the README.md of the Twitter Source.

---

build.gradle

Update to 4.0

---

debezium/README.md
debezium/src/test/java/com/hazelcast/jet/contrib/debezium/MySqlIntegrationTest.java

README and test improvements
- fixes #

Update README and the test

---

debezium/src/test/java/com/hazelcast/jet/contrib/debezium/MsSqlIntegrationTest.java
debezium/src/test/resources/mssql/cdc.sql
debezium/src/test/resources/mssql/check.sql
debezium/src/test/resources/mssql/setup.sql

Added a condition before a test start to make sure required services are running and configured properly.
- fixes #54

Make sure sql server agent has started and cdc is enabled for database

---

kafka-connect/src/main/java/com/hazelcast/jet/contrib/connect/KafkaConnectSources.java
kafka-connect/src/main/java/com/hazelcast/jet/contrib/connect/impl/AbstractKafkaConnectSource.java
mongodb/build.gradle

CDC connector code (#53) needs to move to the main jet repo. To make that possible there are a few changes that need to get into the contrib master repo, and implicitly in the contrib snapshot first. These are those changes.

Adjust Kafka Connect source with changes needed by CDC

---

build.gradle

Bump Jet and Hazelcast dependencies to the latest released ones

---

pulsar/README.md

Enhance the Pulsar connector documentation. Address the reviews of Vladimir.

Update the README.md of the Pulsar connector.

---

build.gradle

This PR updates the versions of Jet and IMDG used in modules (I chose the IMDG version same as Jet 4.3).

Upgrade Jet and IMDG versions

---

http/build.gradle
mqtt/build.gradle
pulsar/build.gradle

Shadow Undertow and its dependencies for Http Connector
Shadow Paho Java Client for Mqtt Connector
I've also excluded findbugs from pulsar connector

Shadow Undertow and Paho client

---

mqtt/build.gradle
mqtt/src/test/java/com/hazelcast/jet/contrib/mqtt/AbstractMqttSourceTest.java
mqtt/src/test/java/com/hazelcast/jet/contrib/mqtt/MosquittoContainer.java
mqtt/src/test/java/com/hazelcast/jet/contrib/mqtt/MqttSinkTest.java
mqtt/src/test/java/com/hazelcast/jet/contrib/mqtt/MqttSourceTest.java
mqtt/src/test/java/com/hazelcast/jet/contrib/mqtt/SecuredMosquittoContainer.java
mqtt/src/test/java/com/hazelcast/jet/contrib/mqtt/SecuredMqttSourceTest.java
mqtt/src/test/resources/mosquitto_secured.conf
mqtt/src/test/resources/passwordfile

Added some smoke tests for using auth in mqtt connector.

Add test for MQTT auth

---

hazelcast-jet-spring-boot-starter/build.gradle
hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/actuate/autoconfigure/HazelcastJetHealthIndicatorAutoConfiguration.java

Update Spring version to 2.4.0
- fixes https://github.com/hazelcast/hazelcast-jet-contrib/issues/99

Update Spring version to 2.4.0
